# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    chocolatey:
      repo: "puppetlabs/chocolatey"
      ref:  "3.1.1"
    powershell:
      repo: "puppetlabs/powershell"
      ref:  "2.1.5"
    registry:
      repo: "puppetlabs/registry"
      ref:  "2.0.2"
    stdlib: 
      repo: "puppetlabs/stdlib"
      ref:  "5.0.0"
