---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
      - gem: 'puppet-strings'

Rakefile:
  requires:
    - 'puppet-strings/tasks'

spec/spec_helper.rb:
  mock_with: ':rspec'

spec/default_facts.yml:
  extra_facts:
    ipaddress6: FE80:0000:0000:0000:AAAA:AAAA:AAAA

.gitlab-ci.yml:
  delete: true
