---
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator

Rakefile:
  requires:
    - 'puppet-strings/tasks'

spec/spec_helper.rb:
  mock_with: ':rspec'

spec/default_facts.yml:
  extra_facts:
    ipaddress6: FE80:0000:0000:0000:AAAA:AAAA:AAAA

.gitlab-ci.yml:
  delete: true

appveyor.yml:
  delete: true
  
.travis.yml:
  delete: true

.github/workflows/auto_release.yml:
  unmanaged: false

.github/workflows/release.yml:
  unmanaged: false

.github/workflows/pr_test.yml:
  unmanaged: false

.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
